name = "Sacred Call"
author = "Dunimark"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73e02297590693ea4d0baa7b8e0e03a9485c7297bd597953247a3ec7fc9b7117"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = []
